### ISSUE TITLE
integration tests

### ISSUE THREAD

**Issue by danryan** [revily/revily#2]

**Comment by pfhawkins** [comment]
Are you planning on forgoing these tests entirely? Or would assistance in this area be welcome?

**Comment by danryan** [comment]
They're done, essentially. I added missing tests a while back as part of a larger refactoring project. API specs flex the full stack from the perspective of an API client (including authentication and authorization), and can be found in `spec/api`.

**Comment by pfhawkins** [comment]
Ah, that makes sense :hamburger:
