### ISSUE TITLE
replace figaro with dotenv

### ISSUE THREAD

**Issue by danryan** [revily/revily#26]
I dislike the application.yml requirement of figaro. dotenv is much more similar to Heroku's .env file construct, which is familiar and easier.

**Comment by pfhawkins** [comment]
Looks like you already switched over to dotenv without closing this issue:

<pre>
{9:10}[2.0.0-p247]~/projects/reveille:dotenv ✗ ➭ grep -i figaro Gemfile
{9:10}[2.0.0-p247]~/projects/reveille:dotenv ✗ ➭ grep -i dotenv Gemfile
gem 'dotenv-rails',                        '0.8.0'
</pre>

**Comment by danryan** [comment]
Indeed. Fixed as of 2339a2b21695d4536047aa5c6236f9df4fbd30fe. Appreciate the reminder :stars:
