### ISSUE TITLE
Rename project to "Revily"

### ISSUE THREAD

**Issue by danryan** [revily/revily#31]
1. "Reveille" is mis-pronounced by almost everyone.
2. "Revily" is hard to get wrong.
3. "Revily" is actually pronounced correctly by text-to-speech systems.
4. revi.ly was available and is a kick-ass short URL
5. It can be trademarked. (I submitted by application to the USPTO last night)
6. The twitter username is inactive, making it way more likely to be given to us.
7. It's the most popular misspelling of reveille.
8. I hate it when projects are difficult to google _/me looks at Chef_

**Comment by pfhawkins** [comment]
I am possibly the only person I know who a) knows how to pronounce "reveille" and b) thought that "revily" was an adjectification of "revile" when I first saw it just now.

Overall a sound decision.

![mybrand](https://f.cloud.github.com/assets/5287/867253/ecd17e6e-f6e2-11e2-9638-7a518ff5230e.gif)

**Comment by seeingidog** [comment]
:thumbsup: by the english nazi. Proceed.

**Comment by trobrock** [comment]
:+1: just for the URL

**Comment by pfhawkins** [comment]
You should grab @revilyapp on twitter on the off chance you can't get @revily.
